spring.profiles.active=${APP_PROFILE:devResend}

spring.sendgrid.api-key=${SENDGRID_API_KEY:test_value}

email.provider=resend
email.api-key=${RESEND_API_KEY}
email.from-address=matcamp1981@gmail.com
email.from-name=integrations